-- MySQL Script generated by MySQL Workbench
-- Thu Jan  9 15:38:36 2020
-- Model: Architecture de donnée    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`EnumNationnality`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`EnumNationnality` ;

CREATE TABLE IF NOT EXISTS `mydb`.`EnumNationnality` (
  `idNat` INT NOT NULL AUTO_INCREMENT,
  `nationnality` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idNat`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`City`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`City` ;

CREATE TABLE IF NOT EXISTS `mydb`.`City` (
  `CPCity` INT NOT NULL,
  `NameCity` VARCHAR(45) NOT NULL,
  `idCity` INT NOT NULL,
  PRIMARY KEY (`idCity`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`DemoInformations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`DemoInformations` ;

CREATE TABLE IF NOT EXISTS `mydb`.`DemoInformations` (
  `NumSecu` INT NOT NULL,
  `Name` VARCHAR(65) NOT NULL,
  `FirstName` VARCHAR(65) NOT NULL,
  `BirthDate` DATE NOT NULL,
  `Adress` VARCHAR(65) NOT NULL,
  `Sexe` CHAR(1) NOT NULL,
  `Profession` VARCHAR(45) NULL,
  `FamilialSituation` VARCHAR(45) NULL,
  `PersonToContact_idPatient` INT NOT NULL,
  `PhoneNumber` VARCHAR(11) NULL,
  `EnumNationnality_idNat` INT NOT NULL,
  `City_idCity` INT NOT NULL,
  `Poid` DOUBLE NULL,
  `Taille` DOUBLE NULL,
  PRIMARY KEY (`NumSecu`),
  INDEX `fk_DemoInformations_EnumNationnality1_idx` (`EnumNationnality_idNat` ASC) VISIBLE,
  INDEX `fk_DemoInformations_City1_idx` (`City_idCity` ASC) VISIBLE,
  CONSTRAINT `fk_DemoInformations_EnumNationnality1`
    FOREIGN KEY (`EnumNationnality_idNat`)
    REFERENCES `mydb`.`EnumNationnality` (`idNat`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DemoInformations_City1`
    FOREIGN KEY (`City_idCity`)
    REFERENCES `mydb`.`City` (`idCity`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`DMP`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`DMP` ;

CREATE TABLE IF NOT EXISTS `mydb`.`DMP` (
  `UUID` INT NOT NULL AUTO_INCREMENT,
  `idDoctor` INT NOT NULL,
  `DemoInformations_NumSecu` INT NOT NULL,
  PRIMARY KEY (`UUID`),
  INDEX `fk_DMP_DemoInformations1_idx` (`DemoInformations_NumSecu` ASC) VISIBLE,
  CONSTRAINT `fk_DMP_DemoInformations1`
    FOREIGN KEY (`DemoInformations_NumSecu`)
    REFERENCES `mydb`.`DemoInformations` (`NumSecu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`DocumentType`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`DocumentType` ;

CREATE TABLE IF NOT EXISTS `mydb`.`DocumentType` (
  `idDocumentType` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  PRIMARY KEY (`idDocumentType`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ChampsObligatoire`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`ChampsObligatoire` ;

CREATE TABLE IF NOT EXISTS `mydb`.`ChampsObligatoire` (
  `Name` VARCHAR(45) NOT NULL,
  `Value` VARCHAR(45) NULL,
  PRIMARY KEY (`Name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`StreamExtension`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`StreamExtension` ;

CREATE TABLE IF NOT EXISTS `mydb`.`StreamExtension` (
  `idStream` INT NOT NULL,
  `LinkStream` VARCHAR(100) NULL,
  PRIMARY KEY (`idStream`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TypeRigth`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`TypeRigth` ;

CREATE TABLE IF NOT EXISTS `mydb`.`TypeRigth` (
  `idTypeRigth` INT NOT NULL,
  `NameTypeRigth` VARCHAR(45) NULL,
  PRIMARY KEY (`idTypeRigth`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`EnumStaffType`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`EnumStaffType` ;

CREATE TABLE IF NOT EXISTS `mydb`.`EnumStaffType` (
  `idEnumStaffType` INT NOT NULL AUTO_INCREMENT,
  `JobName` VARCHAR(45) NULL,
  `WebsiteRigth` VARCHAR(45) NULL,
  `TypeRigth_idTypeRigth` INT NOT NULL,
  PRIMARY KEY (`idEnumStaffType`),
  INDEX `fk_EnumStaffType_TypeRigth1_idx` (`TypeRigth_idTypeRigth` ASC) VISIBLE,
  CONSTRAINT `fk_EnumStaffType_TypeRigth1`
    FOREIGN KEY (`TypeRigth_idTypeRigth`)
    REFERENCES `mydb`.`TypeRigth` (`idTypeRigth`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Unit`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Unit` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Unit` (
  `idHospital` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NULL,
  `Type` INT NULL,
  `Director` INT NOT NULL,
  `rataché` INT NOT NULL,
  `DemandeExamen_idDemandeExamen` INT NOT NULL,
  `DMP_UUID` INT NOT NULL,
  PRIMARY KEY (`idHospital`),
  INDEX `fk_Hospital_StaffMember1_idx` (`Director` ASC) VISIBLE,
  INDEX `fk_Hospital_Hospital1_idx` (`rataché` ASC) VISIBLE,
  INDEX `fk_Unit_DMP1_idx` (`DMP_UUID` ASC) VISIBLE,
  CONSTRAINT `fk_Hospital_StaffMember1`
    FOREIGN KEY (`Director`)
    REFERENCES `mydb`.`StaffMember` (`idStaffMember`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Hospital_Hospital1`
    FOREIGN KEY (`rataché`)
    REFERENCES `mydb`.`Unit` (`idHospital`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Unit_DMP1`
    FOREIGN KEY (`DMP_UUID`)
    REFERENCES `mydb`.`DMP` (`UUID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`StaffMember`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`StaffMember` ;

CREATE TABLE IF NOT EXISTS `mydb`.`StaffMember` (
  `idStaffMember` INT NOT NULL,
  `Skills` LONGTEXT NULL,
  `EnumStaffType_idEnumStaffType` INT NOT NULL,
  `ApplicationUser_idUser` INT NOT NULL,
  `DemoInformations_NumSecu` INT NOT NULL,
  `IBAN` VARCHAR(27) NULL,
  `BIC` VARCHAR(11) NULL,
  `HospitalUnit_idHospitalUnit` INT NULL,
  `Hospital_idHospital` INT NOT NULL,
  `Hospital_StaffMember_idStaffMember` INT NOT NULL,
  `NbBureau` INT NULL,
  PRIMARY KEY (`idStaffMember`),
  INDEX `fk_StaffMember_EnumStaffType1_idx` (`EnumStaffType_idEnumStaffType` ASC) VISIBLE,
  INDEX `fk_StaffMember_DemoInformations1_idx` (`DemoInformations_NumSecu` ASC) VISIBLE,
  INDEX `fk_StaffMember_Hospital1_idx` (`Hospital_idHospital` ASC, `Hospital_StaffMember_idStaffMember` ASC) VISIBLE,
  CONSTRAINT `fk_StaffMember_EnumStaffType1`
    FOREIGN KEY (`EnumStaffType_idEnumStaffType`)
    REFERENCES `mydb`.`EnumStaffType` (`idEnumStaffType`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_StaffMember_DemoInformations1`
    FOREIGN KEY (`DemoInformations_NumSecu`)
    REFERENCES `mydb`.`DemoInformations` (`NumSecu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_StaffMember_Hospital1`
    FOREIGN KEY (`Hospital_idHospital` , `Hospital_StaffMember_idStaffMember`)
    REFERENCES `mydb`.`Unit` (`idHospital` , `Director`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Acte`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Acte` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Acte` (
  `MedicalFolder_idFolder` INT NOT NULL,
  `idActe` VARCHAR(45) NOT NULL,
  `Nom` VARCHAR(45) NULL,
  `DateDebut` DATE NULL,
  `DateFin` DATE NULL,
  `Responsable` INT NOT NULL,
  `Prix` INT NULL,
  INDEX `fk_Acte_MedicalFolder1_idx` (`MedicalFolder_idFolder` ASC) VISIBLE,
  PRIMARY KEY (`idActe`),
  INDEX `fk_Acte_StaffMember1_idx` (`Responsable` ASC) VISIBLE,
  CONSTRAINT `fk_Acte_MedicalFolder1`
    FOREIGN KEY (`MedicalFolder_idFolder`)
    REFERENCES `mydb`.`DMP` (`UUID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Acte_StaffMember1`
    FOREIGN KEY (`Responsable`)
    REFERENCES `mydb`.`StaffMember` (`idStaffMember`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`MedicalDocument`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`MedicalDocument` ;

CREATE TABLE IF NOT EXISTS `mydb`.`MedicalDocument` (
  `idMedicalDocument` INT NOT NULL,
  `DocumentName` VARCHAR(45) NOT NULL,
  `IsADraft` TINYINT NULL,
  `Date` DATE NULL,
  `DocumentLink` VARCHAR(45) NULL,
  `DocumentType_idDocumentType` INT NOT NULL,
  `ChampsObligatoire_Name` VARCHAR(45) NOT NULL,
  `Stream_Extension` INT NOT NULL,
  `Acte_idActe` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idMedicalDocument`),
  INDEX `fk_MedicalDocument_DocumentType1_idx` (`DocumentType_idDocumentType` ASC) VISIBLE,
  INDEX `fk_MedicalDocument_ChampsObligatoire1_idx` (`ChampsObligatoire_Name` ASC) VISIBLE,
  INDEX `fk_MedicalDocument_Stream2_idx` (`Stream_Extension` ASC) VISIBLE,
  INDEX `fk_MedicalDocument_Acte1_idx` (`Acte_idActe` ASC) VISIBLE,
  CONSTRAINT `fk_MedicalDocument_DocumentType1`
    FOREIGN KEY (`DocumentType_idDocumentType`)
    REFERENCES `mydb`.`DocumentType` (`idDocumentType`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_MedicalDocument_ChampsObligatoire1`
    FOREIGN KEY (`ChampsObligatoire_Name`)
    REFERENCES `mydb`.`ChampsObligatoire` (`Name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_MedicalDocument_Stream2`
    FOREIGN KEY (`Stream_Extension`)
    REFERENCES `mydb`.`StreamExtension` (`idStream`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_MedicalDocument_Acte1`
    FOREIGN KEY (`Acte_idActe`)
    REFERENCES `mydb`.`Acte` (`idActe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ApplicationUser`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`ApplicationUser` ;

CREATE TABLE IF NOT EXISTS `mydb`.`ApplicationUser` (
  `Login` VARCHAR(45) NOT NULL,
  `PassWord` VARCHAR(45) NULL,
  `Mail` VARCHAR(50) NULL,
  PRIMARY KEY (`Login`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Constant`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Constant` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Constant` (
  `idConstant` INT NOT NULL,
  `NameConstant` VARCHAR(45) NULL,
  `ValueReferenceMin` DECIMAL NULL,
  `ValueReferenceMax` DECIMAL NULL,
  PRIMARY KEY (`idConstant`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Page`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Page` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Page` (
  `idPage` INT NOT NULL,
  `LinkPage` VARCHAR(100) NULL,
  PRIMARY KEY (`idPage`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Page_has_TypeRigth`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Page_has_TypeRigth` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Page_has_TypeRigth` (
  `Page_idPage` INT NOT NULL,
  `TypeRigth_idTypeRigth` INT NOT NULL,
  PRIMARY KEY (`Page_idPage`, `TypeRigth_idTypeRigth`),
  INDEX `fk_Page_has_TypeRigth_TypeRigth1_idx` (`TypeRigth_idTypeRigth` ASC) VISIBLE,
  INDEX `fk_Page_has_TypeRigth_Page1_idx` (`Page_idPage` ASC) VISIBLE,
  CONSTRAINT `fk_Page_has_TypeRigth_Page1`
    FOREIGN KEY (`Page_idPage`)
    REFERENCES `mydb`.`Page` (`idPage`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Page_has_TypeRigth_TypeRigth1`
    FOREIGN KEY (`TypeRigth_idTypeRigth`)
    REFERENCES `mydb`.`TypeRigth` (`idTypeRigth`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Langue`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Langue` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Langue` (
  `idLangue` VARCHAR(2) NOT NULL,
  `Pays` VARCHAR(45) NULL,
  PRIMARY KEY (`idLangue`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`String`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`String` ;

CREATE TABLE IF NOT EXISTS `mydb`.`String` (
  `idString` VARCHAR(45) NOT NULL,
  `StringContent` VARCHAR(45) NULL,
  `Langue_idLangue` VARCHAR(2) NOT NULL,
  PRIMARY KEY (`idString`),
  INDEX `fk_String_Langue1_idx` (`Langue_idLangue` ASC) VISIBLE,
  CONSTRAINT `fk_String_Langue1`
    FOREIGN KEY (`Langue_idLangue`)
    REFERENCES `mydb`.`Langue` (`idLangue`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Affectation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Affectation` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Affectation` (
  `idAffectation` INT NOT NULL,
  `Symptome` VARCHAR(255) NULL,
  `Acte_idActe` VARCHAR(45) NOT NULL,
  `Unit_idHospital` INT NOT NULL,
  PRIMARY KEY (`idAffectation`, `Acte_idActe`, `Unit_idHospital`),
  INDEX `fk_Affectation_Acte1_idx` (`Acte_idActe` ASC) VISIBLE,
  INDEX `fk_Affectation_Unit1_idx` (`Unit_idHospital` ASC) VISIBLE,
  CONSTRAINT `fk_Affectation_Acte1`
    FOREIGN KEY (`Acte_idActe`)
    REFERENCES `mydb`.`Acte` (`idActe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Affectation_Unit1`
    FOREIGN KEY (`Unit_idHospital`)
    REFERENCES `mydb`.`Unit` (`idHospital`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Responsable`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Responsable` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Responsable` (
  `StaffMember_idStaffMember` INT NOT NULL,
  `DMP_UUID` INT NOT NULL,
  PRIMARY KEY (`StaffMember_idStaffMember`, `DMP_UUID`),
  INDEX `fk_StaffMember_has_DMP_DMP1_idx` (`DMP_UUID` ASC) VISIBLE,
  INDEX `fk_StaffMember_has_DMP_StaffMember1_idx` (`StaffMember_idStaffMember` ASC) VISIBLE,
  CONSTRAINT `fk_StaffMember_has_DMP_StaffMember1`
    FOREIGN KEY (`StaffMember_idStaffMember`)
    REFERENCES `mydb`.`StaffMember` (`idStaffMember`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_StaffMember_has_DMP_DMP1`
    FOREIGN KEY (`DMP_UUID`)
    REFERENCES `mydb`.`DMP` (`UUID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
